version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  cyclop:
    max-complexity: 25

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - errcheck
    
    # Исключаем datasources и provider из проверки сложности
    # так как они содержат стандартные функции Terraform провайдера
    - path: internal/datasources/
      linters:
        - cyclop
    
    - path: internal/provider/
      linters:
        - cyclop
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 